# Generated by Django 4.2.1 on 2024-06-12 19:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Uzytkownik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategoria', models.CharField(max_length=255)),
                ('ocena', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wypozyczalnia.uzytkownik')),
                ('tytul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wypozyczalnia.ksiazka')),
            ],
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='kategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wypozyczalnia.recenzja'),
        ),
    ]
