# Generated by Django 4.2.1 on 2024-06-12 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recenzja',
            old_name='autor',
            new_name='autor_rec',
        ),
        migrations.RenameField(
            model_name='uzytkownik',
            old_name='autor',
            new_name='autor_rec',
        ),
        migrations.RemoveField(
            model_name='ksiazka',
            name='kategoria',
        ),
    ]
