# Generated by Django 4.2.13 on 2024-06-13 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wypozyczalnia', '0004_alter_ksiazka_id_alter_recenzja_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recenzja',
        ),
        migrations.DeleteModel(
            name='Uzytkownik',
        ),
    ]
