# Generated by Django 4.2.13 on 2024-06-17 06:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('kategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.kategoria')),
            ],
        ),
        migrations.CreateModel(
            name='SzukanaKsiazka',
            fields=[
                ('ksiazka_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wypozyczalnia.ksiazka')),
            ],
            bases=('wypozyczalnia.ksiazka',),
        ),
        migrations.CreateModel(
            name='Recenzja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinia', models.TextField()),
                ('ocena', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('autor_rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ksiazka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wypozyczalnia.ksiazka')),
            ],
        ),
    ]
