# Generated by Django 4.2.13 on 2024-06-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ksiazka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('opis', models.CharField(max_length=255)),
            ],
        ),
    ]
