# Generated by Django 4.2.13 on 2024-06-14 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ksiazka',
            name='opis',
            field=models.TextField(),
        ),
    ]
