# Generated by Django 4.2.13 on 2024-06-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalnia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recenzja',
            name='ksiazka',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ksiazeczka', to='wypozyczalnia.ksiazka'),
        ),
    ]
